### ISSUE TITLE
Setup docs

### ISSUE THREAD

**Issue by DynamoRed** [DynamoRed/pa_esgi_2021_22#1]
- [x] Descriptif fonctionnel détaillé et numéroté de la partie Application Web

- [x] Descriptif fonctionnel détaillé et numéroté de la partie C
- [x] Première matrice RACI et premier diagramme Gantt

**Comment by DynamoRed** [comment]
Descriptif Fonctionnel Application Web:
https://docs.google.com/document/d/182JbDpfnEB8n-axDZfHsCDzC1ArsXIgvg8YsRCxlsXo/edit?usp=sharing

**Comment by DynamoRed** [comment]
## Descriptif Fonctionnel Application Web - **V1**
[Descriptif Fonctionnel Application Web - PA 2021-22 ESGI.pdf](https://github.com/DynamoRed/pa_esgi_2021_22/files/7928870/Descriptif.Fonctionnel.Application.Web.-.PA.2021-22.ESGI.pdf)

**Comment by DynamoRed** [comment]
## Descriptif Fonctionne Application C - V1
[Descriptif Fonctionnel Application C - PA 2021-22 ESGI.pdf](https://github.com/DynamoRed/pa_esgi_2021_22/files/7959226/Descriptif.Fonctionnel.Application.C.-.PA.2021-22.ESGI.pdf)

**Comment by Maubry94** [comment]
Digramme de Gantt - V1

![Diagramme de Gantt PA](https://user-images.githubusercontent.com/58041322/151578135-2a05b126-c7f0-4d1c-93e7-499a56b44e24.png)

**Comment by DynamoRed** [comment]
## Matrice RACI - V1
<img src="https://user-images.githubusercontent.com/44113746/151582763-577164b5-ab63-4dc3-bb1b-523dc390d2b6.png" height="600px" />
