### ISSUE TITLE
Financial costing

### ISSUE THREAD

**Issue by DynamoRed** [DynamoRed/pa_esgi_2021_22#2]
- [x] Planification des différentes tâches à réaliser, chiffrage financier de la partie développement

**Comment by Maubry94** [comment]
Chiffrage financier de développement V1
Reprise de l'ensemble des coûts avec proposition d'une offre commerciale - Mission 3 V1

[Chiffrage_Financier_Developpement.xlsx](https://github.com/DynamoRed/pa_esgi_2021_22/files/7918276/Chiffrage_Financier_Developpement.xlsx)

[Reprise_de_lensemble_des_couts_avec_proposition_dune_offre_commerciale_-_Mission_3.xlsx](https://github.com/DynamoRed/pa_esgi_2021_22/files/7918278/Reprise_de_lensemble_des_couts_avec_proposition_dune_offre_commerciale_-_Mission_3.xlsx)

**Comment by Maubry94** [comment]
Chiffrage financier de développement V2
Reprise de l'ensemble des coûts avec proposition d'une offre commerciale - Mission 3 V2

[Chiffrage Financier Developpement.xlsx](https://github.com/DynamoRed/pa_esgi_2021_22/files/7957874/Chiffrage.Financier.Developpement.xlsx)

[Reprise de l'ensemble des coûts avec proposition d'une offre commerciale - Mission 3.xlsx](https://github.com/DynamoRed/pa_esgi_2021_22/files/7957878/Reprise.de.l.ensemble.des.couts.avec.proposition.d.une.offre.commerciale.-.Mission.3.xlsx)
