### ISSUE TITLE
Design website & project identity

### ISSUE THREAD

**Issue by DynamoRed** [DynamoRed/pa_esgi_2021_22#3]
- [x] #5

- [x] Logo du projet

- [x] Charte graphique avec exemples

- [x] Maquette WEB definitive (Plan du site (arborescence))

- [x] #8

**Comment by Dropaa** [comment]
Bonne description du Label

**Comment by DynamoRed** [comment]
Première proposition de logo:

![logo-prop2](https://user-images.githubusercontent.com/44113746/150562288-afd11053-f43b-4903-8405-570f4661a7db.png)
![logo-prop1](https://user-images.githubusercontent.com/44113746/150562292-03d7ffd1-3c9f-4782-9fa8-a598ec6d12c5.png)

**Comment by DynamoRed** [comment]
Seconde proposition de logo:

![logo-prop4](https://user-images.githubusercontent.com/44113746/150562383-bec24cad-a743-4207-86c6-10bacad16478.png)
![logo-prop3](https://user-images.githubusercontent.com/44113746/150562387-db772a70-c5a0-48f1-bc6b-c7218a24f9cd.png)

**Comment by Maubry94** [comment]
Je suis pour celle-là !

**Comment by DynamoRed** [comment]
Pareil pour moi, j'ai une preference pour la seconde

**Comment by Dropaa** [comment]
Je préfère le dernier design !

**Comment by DynamoRed** [comment]
# Logo
### ✅ Seconde proposition choisie

**Comment by DynamoRed** [comment]
![Charte Graphique](https://user-images.githubusercontent.com/44113746/150696750-0cc7d3a2-5974-4cbe-b3a6-83487e5a92d2.png)

**Comment by DynamoRed** [comment]
## Arborescence Web

📂 web/
┣ 📂 cdn/
┃ ┣  📂 js/
┃ ┃   ┗  _JS Files_
┃ ┃
┃ ┣  📂 attachments/
┃ ┃   ┗ _Images Files_
┃ ┃
┃ ┣ 📂 css/
┃ ┃   ┗ _CSS Stylesheets_
┃ ┃
┃ ┗ 📂 icons/
┃   ┗   _Icons pack_
┃
┣ 📂 api/
┃ ┗ ⚙️ Laravel App
┃
┣ 📂 main/
┃ ┗ ⚙️ Nuxt.js App
┃
┗ 📂 panel/
   ┗ ⚙️ Nuxt.js App

**Comment by DynamoRed** [comment]
## Maquette Web
https://www.figma.com/file/5I1SDePCiZadmLSF2ThzhT/Untitled?node-id=0%3A1
