### ISSUE TITLE
CUrl test & firewall search

### ISSUE THREAD

**Issue by DynamoRed** [DynamoRed/pa_esgi_2021_22#4]
- [x] Rendre et présenter un programme de test sur l'utilisation de Curl

- [x] Commencer les recherches sur les Firewall PFSENSE ou OPNSENSE et les VPN site à site (IPSEC par exemple)

**Comment by Dropaa** [comment]
-Installation de vsftpd sur la deuxième VM afin de pouvoir transferer via FTP.
-Installation de ufw (firewall) et ouverture des ports 20:21/tcp et des ports 1024:65535/tcp
-Création du code transférant un fichier d'une VM A à une VM B via cURL utilisant le protocole FTP
-Création d'un code permettant de récupérer un fichier depuis une autre VM via cURL utilisant le protocole FTP

**Comment by Dropaa** [comment]
[Code curl PA.zip](https://github.com/DynamoRed/pa_esgi_2021_22/files/7928454/Code.curl.PA.zip)

**Comment by Dropaa** [comment]
Après recherche, 
-pfSense n'a pas de mise à jour régulières contrairement à OPNsense qui en possède fréquemment.
-OPNsense basé sur HardenedBSD plutôt que FreeBSD
-OPNsense possède une meilleur interface mise à jour et plus détaillée.
-OPNsense possède beaucoup plus de plugins que pfSense et il est automatique. De plus, il possède un système de backup chiffrés vers GoogleDrive ou NexCloud.
-La meilleure organisation de l'UI (User Interface) reviens à OPNsense.
On peut donc affirmer que en général, il serais plus avantageux d'utiliser **OPNsense** que pfSense.

L'IPSec permet de sécuriser les données envoyées sur les réseaux publics. IPsec est souvent utilisé pour mettre en place des réseaux privés virtuels (VPN). Il fonctionne en cryptant les paquets IP ; tout en authentifiant la source d’où proviennent les paquets.
Pourquoi devrais-t-on utiliser IPsec pour le projet ?
Les VPN permettent d’accéder et d’échanger des données confidentielles en toute sécurité sur des infrastructures de réseau partagées ; comme l’internet public par exemple. Ils vont établir une connexion et créer un tunnel sécurisé.

Pour la sécurité du projet, il est donc intéressant et recommandé d'utiliser IPSec pour un VPN.
