### ISSUE TITLE
Nom du projet

### ISSUE THREAD

**Issue by DynamoRed** [DynamoRed/pa_esgi_2021_22#5]
Suggestions de noms:

**Comment by DynamoRed** [comment]
~~Hyper Unicorn~~

**Comment by Dropaa** [comment]
IT It

**Comment by DynamoRed** [comment]
Octopus IT

**Comment by DynamoRed** [comment]
IT me

**Comment by Maubry94** [comment]
RMR Inc

**Comment by DynamoRed** [comment]
Lovelace Inc. / Lovelace IT

_(ref. Ada Lovelace)_

**Comment by DynamoRed** [comment]
> RMR Inc

Sympa comme solution "B", classique mais efficace

**Comment by DynamoRed** [comment]
Je vote pour:
> Octopus IT
> RMR Inc.

**Comment by DynamoRed** [comment]
RMR Inc - :white_check_mark: Nom choisi
